defmodule MiwayCreditCore.Notifications do
  @moduledoc """
  Reserved context boundary. Will deliver communications (email/SMS)
  generated by other contexts. It never decides an outcome itself —
  `Applications` decides an application was approved;
  `Notifications` only sends the message that says so.

  No schema, migration, or function exists yet. Implementation is
  unscheduled. See `docs/architecture/context_boundaries.md` for
  ownership, dependencies, and what this context must never do.
  """
end
