defmodule MiwayCreditCore.Notifications do
  @moduledoc """
  Delivery boundary for communications (email/SMS) generated by other
  contexts. It never decides an outcome itself — `Accounts` decides a
  password reset was requested and owns the token's lifecycle;
  `Notifications` only prepares and sends the message that carries the
  link. See docs/architecture/context_boundaries.md for ownership.

  Scoped for now to password-reset email — the only channel/event
  actually wired up. Other event types (approval, rejection, payment
  received) still don't call out here; extend this module with a
  sibling `deliver_*` function per event as each is actually built,
  rather than pre-building unused channels.
  """

  require Logger

  alias MiwayCreditCore.Notifications.{Mailer, PasswordResetEmail}

  @doc """
  Sends the password-reset link email. Returns `:ok` on successful
  handoff to the provider, `{:error, reason}` on delivery failure —
  the caller (`Accounts.PasswordResetNotifier.Email`) never surfaces
  `reason` to the end user; it's logged here, server-side, only.

  `mailer_opts` is Swoosh's own dynamic-config override (merged over
  the configured Mailer adapter/settings) — unused in production,
  where the configured adapter is always right; it exists so a test
  can inject a failing adapter for one call without mutating global
  Application config and risking the async suite.
  """
  def deliver_password_reset_email(user, reset_url, mailer_opts \\ []) do
    user
    |> PasswordResetEmail.build(reset_url)
    |> Mailer.deliver(mailer_opts)
    |> case do
      {:ok, _metadata} ->
        :ok

      {:error, reason} ->
        Logger.error("Password reset email delivery failed for #{user.email}: #{inspect(reason)}")
        {:error, reason}
    end
  end
end
